import { PlayerColor } from "../../API/fields/player/PlayerColor"

export abstract class PlayerColors {
    static readonly RED = PlayerColor.convert(0)
    static readonly BLUE = PlayerColor.convert(1)
    static readonly CYAN = PlayerColor.convert(2)
    static readonly PURPLE = PlayerColor.convert(3)
    static readonly YELLOW = PlayerColor.convert(4)
    static readonly ORANGE = PlayerColor.convert(5)
    static readonly GREEN = PlayerColor.convert(6)
    static readonly PINK = PlayerColor.convert(7)
    static readonly LIGHT_GRAY = PlayerColor.convert(8)
    static readonly LIGHT_BLUE = PlayerColor.convert(9)
    static readonly AQUA = PlayerColor.convert(10)
    static readonly BROWN = PlayerColor.convert(11)
    static readonly MAROON = PlayerColor.convert(12)
    static readonly NAVY = PlayerColor.convert(13)
    static readonly TURQUOISE = PlayerColor.convert(14)
    static readonly VIOLET = PlayerColor.convert(15)
    static readonly WHEAT = PlayerColor.convert(16)
    static readonly PEACH = PlayerColor.convert(17)
    static readonly MINT = PlayerColor.convert(18)
    static readonly LAVENDER = PlayerColor.convert(19)
    static readonly COAL = PlayerColor.convert(20)
    static readonly SNOW = PlayerColor.convert(21)
    static readonly EMERALD = PlayerColor.convert(22)
    static readonly PEANUT = PlayerColor.convert(23)
}
