import { PlayerColor } from "../../API/fields/player/PlayerColor"

export abstract class PlayerColors {
    public static readonly RED = new PlayerColor(0)
    public static readonly BLUE = new PlayerColor(1)
    public static readonly CYAN = new PlayerColor(2)
    public static readonly PURPLE = new PlayerColor(3)
    public static readonly YELLOW = new PlayerColor(4)
    public static readonly ORANGE = new PlayerColor(5)
    public static readonly GREEN = new PlayerColor(6)
    public static readonly PINK = new PlayerColor(7)
    public static readonly LIGHT_GRAY = new PlayerColor(8)
    public static readonly LIGHT_BLUE = new PlayerColor(9)
    public static readonly AQUA = new PlayerColor(10)
    public static readonly BROWN = new PlayerColor(11)
    public static readonly MAROON = new PlayerColor(12)
    public static readonly NAVY = new PlayerColor(13)
    public static readonly TURQUOISE = new PlayerColor(14)
    public static readonly VIOLET = new PlayerColor(15)
    public static readonly WHEAT = new PlayerColor(16)
    public static readonly PEACH = new PlayerColor(17)
    public static readonly MINT = new PlayerColor(18)
    public static readonly LAVENDER = new PlayerColor(19)
    public static readonly COAL = new PlayerColor(20)
    public static readonly SNOW = new PlayerColor(21)
    public static readonly EMERALD = new PlayerColor(22)
    public static readonly PEANUT = new PlayerColor(23)
}
