import { AbilityStringLevelField } from "../../../API/fields/ability/level/AbilityStringLevelField";

export abstract class AbilityStringLevelFields {
  public static readonly ICON_NORMAL = new AbilityStringLevelField('aart', 'Пиктограмма: используется')
  public static readonly CASTER = new AbilityStringLevelField('acat', 'Маг')
  public static readonly TARGET = new AbilityStringLevelField('atat', 'Цель')
  public static readonly SPECIAL = new AbilityStringLevelField('asat', 'Особые')
  public static readonly EFFECT = new AbilityStringLevelField('aeat', 'Эффект')
  public static readonly AREA_EFFECT = new AbilityStringLevelField('aaea', 'Область воздействия')
  public static readonly LIGHTNING_EFFECTS = new AbilityStringLevelField('alig', 'Эффекты молнии')
  public static readonly MISSILE_ART = new AbilityStringLevelField('amat', 'Анимация дистанционной атаки')
  public static readonly TOOLTIP_LEARN = new AbilityStringLevelField('aret', 'Подсказка: выучить')
  public static readonly TOOLTIP_EXTENDED_LEARN = new AbilityStringLevelField('arut', 'Подсказка: выучить, подробная')
  public static readonly TOOLTIP_NORMAL = new AbilityStringLevelField('atp1', 'Подсказка: используется, нормальная')
  public static readonly TOOLTIP_TURN_OFF = new AbilityStringLevelField('aut1', 'Подсказка: не используется')
  public static readonly TOOLTIP_EXTENDED_NORMAL = new AbilityStringLevelField('aub1', 'Подсказка: используется, подробная')
  public static readonly TOOLTIP_EXTENDED_TURN_OFF = new AbilityStringLevelField('auu1', 'Подсказка: не используется, подробная')
  public static readonly NORMAL_FORM_UNIT_EME1 = new AbilityStringLevelField('Eme1', 'Нормальная форма боевой единицы', 'Перевоплощение')
  public static readonly SPAWNED_UNITS = new AbilityStringLevelField('Ndp1', 'Войска', 'Темные врата (Архимонд)')
  public static readonly ABILITY_FOR_UNIT_CREATION = new AbilityStringLevelField('Nrc1', 'Возможность создания войск', 'Огненный дождь (Архимонд)')
  public static readonly NORMAL_FORM_UNIT_MIL1 = new AbilityStringLevelField('Mil1', 'Нормальная форма боевой единицы', 'К оружию (работник)')
  public static readonly ALTERNATE_FORM_UNIT_MIL2 = new AbilityStringLevelField('Mil2', 'Альтернативная форма боевой единицы', 'К оружию (работник)')
  public static readonly BASE_ORDER_ID_ANS5 = new AbilityStringLevelField('Ans5', 'Базовый ID приказа', 'Поставка ресурсов')
  public static readonly MORPH_UNITS_GROUND = new AbilityStringLevelField('Ply2', 'Превращающиеся войска: наземные', 'Полиморф')
  public static readonly MORPH_UNITS_AIR = new AbilityStringLevelField('Ply3', 'Превращающиеся войска: воздушные', 'Полиморф')
  public static readonly MORPH_UNITS_AMPHIBIOUS = new AbilityStringLevelField('Ply4', 'Превращающиеся войска: амфибии', 'Полиморф')
  public static readonly MORPH_UNITS_WATER = new AbilityStringLevelField('Ply5', 'Превращающиеся войска: вода', 'Полиморф')
  public static readonly UNIT_TYPE_ONE = new AbilityStringLevelField('Rai3', 'Боевая единица первого типа', 'Оживить мертвых')
  public static readonly UNIT_TYPE_TWO = new AbilityStringLevelField('Rai4', 'Боевая единица второго типа', 'Оживить мертвых')
  public static readonly UNIT_TYPE_SOD2 = new AbilityStringLevelField('Sod2', 'Тип войск', 'Скелет (возможно, черная стрела)')
  public static readonly SUMMON_1_UNIT_TYPE = new AbilityStringLevelField('Ist1', 'Вызвать 1: тип войск', 'Предмет: вызов скелета')
  public static readonly SUMMON_2_UNIT_TYPE = new AbilityStringLevelField('Ist2', 'Вызвать 2: тип войск', 'Предмет: вызов скелета')
  public static readonly RACE_TO_CONVERT = new AbilityStringLevelField('Ndc1', 'Конвертируется в расу', 'Обращение во Тьму')
  public static readonly PARTNER_UNIT_TYPE = new AbilityStringLevelField('coa1', 'Тип боевой единицы партнера', 'Оседлать гиппогрифа')
  public static readonly PARTNER_UNIT_ONE_TYPE = new AbilityStringLevelField('dcp1', 'Боевая единица партнера, тип первый', 'Расседлать')
  public static readonly PARTNER_UNIT_TWO_TYPE = new AbilityStringLevelField('dcp2', 'Боевая единица партнера, тип второй', 'Расседлать')
  // не удалось найти в РО
  public static readonly REQUIRED_UNIT_TYPE = new AbilityStringLevelField('tpi1')
  // не удалось найти в РО
  public static readonly CONVERTED_UNIT_TYPE = new AbilityStringLevelField('tpi2')
  public static readonly SPELL_LIST = new AbilityStringLevelField('spb1', 'Список заклинаний', 'Книга заклинаний')
  public static readonly BASE_ORDER_ID_SPB5 = new AbilityStringLevelField('spb5', 'Базовый ID приказа', 'Книга заклинаний')
  public static readonly BASE_ORDER_ID_NCL6 = new AbilityStringLevelField('Ncl6', 'Базовый ID приказа', 'Канал')
  public static readonly ABILITY_UPGRADE_1 = new AbilityStringLevelField('Neg3', 'Усовершенствование способности 1', 'Техника')
  public static readonly ABILITY_UPGRADE_2 = new AbilityStringLevelField('Neg4', 'Усовершенствование способности 2', 'Техника')
  public static readonly ABILITY_UPGRADE_3 = new AbilityStringLevelField('Neg5', 'Усовершенствование способности 3', 'Техника')
  public static readonly ABILITY_UPGRADE_4 = new AbilityStringLevelField('Neg6', 'Усовершенствование способности 4', 'Техника')
  public static readonly SPAWN_UNIT_ID_NSY2 = new AbilityStringLevelField('Nsy2', 'Идентификатор порожденного воина', 'Мини-завод')
}