/** @noSelfInFile **/
// @ts-nocheck

declare const ConvertAbilityBooleanLevelField = (i: number) => abilitybooleanlevelfield

const c = (s: string): abilitybooleanlevelfield => ConvertAbilityBooleanLevelField(FourCC(s))

export const AbilityBooleanLevelField = {
    PercentBonus_Hab2: c("Hab2"),
    UseTeleportClustering_Hmt3: c("Hmt3"),
    NeverMiss_Ocr5: c("Ocr5"),
    ExcludeItemDamage: c("Ocr6"),
    BackstabDamage: c("Owk4"),
    InheritUpgrades_Uan3: c("Uan3"),
    ManaConversionAsPercent: c("Udp3"),
    LifeConversionAsPercent: c("Udp4"),
    LeaveTargetAlive: c("Udp5"),
    PercentBonus_Uau3: c("Uau3"),
    DamageIsPercentReceived: c("Eah2"),
    MeleeBonus: c("Ear2"),
    RangedBonus: c("Ear3"),
    FlatBonus: c("Ear4"),
    NeverMiss_Hbh5: c("Hbh5"),
    PercentBonus_Had2: c("Had2"),
    CanDeactivate: c("Hds1"),
    RaisedUnitsAreInvulnerable: c("Hre2"),
    Percentage_Oar2: c("Oar2"),
    SummonBusyUnits: c("Btl2"),
    CreatesBlight: c("Bli2"),
    ExplodesOnDeath: c("Sds6"),
    AlwaysAutocast_Fae2: c("Fae2"),
    RegenerateOnlyAtNight: c("Mbt5"),
    ShowSelectUnitButton: c("Neu3"),
    ShowUnitIndicator: c("Neu4"),
    ChargeOwningPlayer: c("Ans6"),
    Percentage_Arm2: c("Arm2"),
    TargetIsInvulnerable: c("Pos3"),
    TargetIsMagicImmune: c("Pos4"),
    KillOnCasterDeath: c("Ucb6"),
    NoTargetRequired_Rej4: c("Rej4"),
    AcceptsGold: c("Rtn1"),
    AcceptsLumber: c("Rtn2"),
    PreferHostiles_Roa5: c("Roa5"),
    PreferFriendlies_Roa6: c("Roa6"),
    RootedTurning: c("Roo3"),
    AlwaysAutocast_Slo3: c("Slo3"),
    HideButton: c("Ihid"),
    UseTeleportClustering_Itp2: c("Itp2"),
    ImmuneToMorphEffects: c("Eth1"),
    DoesNotBlockBuildings: c("Eth2"),
    AutoAcquireAttackTargets: c("Gho1"),
    ImmuneToMorphEffects_Gho2: c("Gho2"),
    DoNotBlockBuildings: c("Gho3"),
    IncludeRangedDamage: c("Ssk4"),
    IncludeMeleeDamage: c("Ssk5"),
    MoveToPartner: c("coa2"),
    CanBeDispelled: c("cyc1"),
    IgnoreFriendlyBuffs: c("dvm6"),
    DropItemsOnDeath: c("inv2"),
    CanUseItems: c("inv3"),
    CanGetItems: c("inv4"),
    CanDropItems: c("inv5"),
    RepairsAllowed: c("liq4"),
    CasterOnlySplash: c("mfl6"),
    NoTargetRequired_irl4: c("irl4"),
    DispelOnAttack: c("irl5"),
    AmountIsRawValue: c("ipv3"),
    SharedSpellCooldown: c("spb2"),
    SleepOnce: c("sla1"),
    AllowOnAnyPlayerSlot: c("sla2"),
    DisableOtherAbilities: c("Ncl5"),
    AllowBounty: c("Ntm4")
}
