import { DamageType } from "../../API/fields/unit/DamageType"

export abstract class DamageTypes {
    static readonly UNKNOWN = DamageType.convert(0)
    static readonly NORMAL = DamageType.convert(4)
    static readonly ENHANCED = DamageType.convert(5)
    static readonly FIRE = DamageType.convert(8)
    static readonly COLD = DamageType.convert(9)
    static readonly LIGHTNING = DamageType.convert(10)
    static readonly POISON = DamageType.convert(11)
    static readonly DISEASE = DamageType.convert(12)
    static readonly DIVINE = DamageType.convert(13)
    static readonly MAGIC = DamageType.convert(14)
    static readonly SONIC = DamageType.convert(15)
    static readonly ACID = DamageType.convert(16)
    static readonly FORCE = DamageType.convert(17)
    static readonly DEATH = DamageType.convert(18)
    static readonly MIND = DamageType.convert(19)
    static readonly PLANT = DamageType.convert(20)
    static readonly DEFENSIVE = DamageType.convert(21)
    static readonly DEMOLITION = DamageType.convert(22)
    static readonly SLOW_POISON = DamageType.convert(23)
    static readonly SPIRIT_LINK = DamageType.convert(24)
    static readonly SHADOW_STRIKE = DamageType.convert(25)
    static readonly UNIVERSAL = DamageType.convert(26)
}
