/** @noSelfInFile **/
// @ts-nocheck

declare const ConvertSubAnimType = (i: number) => subanimtype

const c = ConvertSubAnimType

export const SubAnimType = {
    Rooted: c(11),
    AlternateEx: c(12),
    Looping: c(13),
    Slam: c(14),
    Throw: c(15),
    Spiked: c(16),
    Fast: c(17),
    Spin: c(18),
    Ready: c(19),
    Channel: c(20),
    Defend: c(21),
    Victory: c(22),
    Turn: c(23),
    Left: c(24),
    Right: c(25),
    Fire: c(26),
    Flesh: c(27),
    Hit: c(28),
    Wounded: c(29),
    Light: c(30),
    Moderate: c(31),
    Severe: c(32),
    Critical: c(33),
    Complete: c(34),
    Gold: c(35),
    Lumber: c(36),
    Work: c(37),
    Talk: c(38),
    First: c(39),
    Second: c(40),
    Third: c(41),
    Fourth: c(42),
    Fifth: c(43),
    One: c(44),
    Two: c(45),
    Three: c(46),
    Four: c(47),
    Five: c(48),
    Small: c(49),
    Medium: c(50),
    Large: c(51),
    Upgrade: c(52),
    Drain: c(53),
    Fill: c(54),
    ChainLightning: c(55),
    EatTree: c(56),
    Puke: c(57),
    Flail: c(58),
    Off: c(59),
    Swim: c(60),
    Entangle: c(61),
    Berserk: c(62)
}
